2024-11-01 22:53:52,831 ERROR: Traceback: Traceback (most recent call last):
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/validators.py", line 401, in __call__
    import email_validator
ModuleNotFoundError: No module named 'email_validator'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kevin-pesenecker/Documents/code/munch/app/routes.py", line 162, in register
    if form.validate_on_submit():
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/form.py", line 330, in validate
    return super().validate(extra)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/form.py", line 147, in validate
    if not field.validate(self, extra):
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/fields/core.py", line 234, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/fields/core.py", line 254, in _run_validation_chain
    validator(form, self)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/validators.py", line 403, in __call__
    raise Exception(
Exception: Install 'email_validator' for email validation support.
 [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:187]
2024-11-01 22:53:58,567 ERROR: Error during registration: Install 'email_validator' for email validation support. [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:185]
2024-11-01 22:53:58,567 ERROR: Error type: Exception [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:186]
2024-11-01 22:53:58,567 ERROR: Traceback: Traceback (most recent call last):
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/validators.py", line 401, in __call__
    import email_validator
ModuleNotFoundError: No module named 'email_validator'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kevin-pesenecker/Documents/code/munch/app/routes.py", line 162, in register
    if form.validate_on_submit():
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/form.py", line 330, in validate
    return super().validate(extra)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/form.py", line 147, in validate
    if not field.validate(self, extra):
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/fields/core.py", line 234, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/fields/core.py", line 254, in _run_validation_chain
    validator(form, self)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/validators.py", line 403, in __call__
    raise Exception(
Exception: Install 'email_validator' for email validation support.
 [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:187]
2024-11-01 22:54:05,573 ERROR: Error during registration: Install 'email_validator' for email validation support. [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:185]
2024-11-01 22:54:05,573 ERROR: Error type: Exception [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:186]
2024-11-01 22:54:05,574 ERROR: Traceback: Traceback (most recent call last):
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/validators.py", line 401, in __call__
    import email_validator
ModuleNotFoundError: No module named 'email_validator'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kevin-pesenecker/Documents/code/munch/app/routes.py", line 162, in register
    if form.validate_on_submit():
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/form.py", line 330, in validate
    return super().validate(extra)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/form.py", line 147, in validate
    if not field.validate(self, extra):
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/fields/core.py", line 234, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/fields/core.py", line 254, in _run_validation_chain
    validator(form, self)
  File "/home/kevin-pesenecker/micromamba/lib/python3.9/site-packages/wtforms/validators.py", line 403, in __call__
    raise Exception(
Exception: Install 'email_validator' for email validation support.
 [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:187]
2024-11-01 22:55:55,052 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 22:56:23,546 INFO: Starting registration process for username: Kevin Pesenecker [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:163]
2024-11-01 22:56:23,648 INFO: Successfully registered user: Kevin Pesenecker [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:172]
2024-11-01 23:03:52,503 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:04:42,186 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:05:17,981 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:05:37,974 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:06:03,151 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:06:39,632 INFO: Starting registration process for username: Kevin Pesenecker2 [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:163]
2024-11-01 23:06:39,727 INFO: Successfully registered user: Kevin Pesenecker2 [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:172]
2024-11-01 23:11:29,693 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:11:30,298 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:12:00,135 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:13:12,471 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:13:23,466 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:13:58,987 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:13:59,864 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:14:00,709 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:14:55,118 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-01 23:15:12,102 INFO: Starting registration process for username: Kevin Pesenecker3 [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:163]
2024-11-01 23:15:12,196 INFO: Successfully registered user: Kevin Pesenecker3 [in /home/kevin-pesenecker/Documents/code/munch/app/routes.py:172]
2024-11-02 08:46:09,344 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-02 08:57:26,062 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-02 09:02:20,291 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
2024-11-02 09:09:08,055 INFO: Munch startup [in /home/kevin-pesenecker/Documents/code/munch/app/utils/logger.py:15]
